<#
.SYNOPSIS
    Downloads ONNX models for the webcam tracking feature.

.DESCRIPTION
    Pulls the three MediaPipe ONNX models used by Services/WebcamTrackingService.cs
    into Resources/Models/. We mirror them from IntelliProve's `face-detection-onnx`
    GitHub repository (MIT-licensed), which packages clean MediaPipe ONNX exports
    in a single tree with stable raw.githubusercontent.com URLs.

    PRIVACY NOTE: This script is for DEVELOPER BUILD TIME ONLY. The shipped
    application NEVER downloads anything -- models are bundled into the
    installer. End users have zero network involvement with this feature.

    The script:
      1. Skips files that already exist (idempotent -- safe to re-run).
      2. Downloads from upstream URLs.
      3. Verifies the file is at least a sane minimum size.
      4. Computes SHA256 and compares against the pinned values below.
      5. Writes a .sha256 sidecar.

    The companion blazeface_anchors.json file is committed alongside the
    .onnx models (generated by tools/generate-blazeface-anchors.py — a port
    of IntelliProve's _ssd_generate_anchors with SSD_OPTIONS_SHORT). It is
    NOT downloaded here.

.PARAMETER Force
    Re-download even if files already exist.

.PARAMETER VerifyOnly
    Skip downloads. Just print SHA256 of existing files for manual cross-check.

.EXAMPLE
    .\tools\download-webcam-models.ps1
    .\tools\download-webcam-models.ps1 -Force
    .\tools\download-webcam-models.ps1 -VerifyOnly
#>

[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$VerifyOnly
)

$ErrorActionPreference = 'Stop'

# Windows PowerShell 5.1 defaults to TLS 1.0/1.1 which GitHub no longer accepts.
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

$projectRoot = Split-Path -Parent $PSScriptRoot
$modelsDir = Join-Path $projectRoot 'Resources\Models'

if (-not (Test-Path $modelsDir)) {
    New-Item -ItemType Directory -Path $modelsDir -Force | Out-Null
}

# Pinned upstream URLs and SHA256s (verified 2026-04-26 against IntelliProve
# main branch). Update these together if upstream rotates.
$models = @(
    [PSCustomObject]@{
        Name        = 'face_detection_short_range.onnx'
        Description = 'BlazeFace short-range face detector (~409 KB)'
        Url         = 'https://raw.githubusercontent.com/IntelliProve/face-detection-onnx/main/fdlite/data/face_detection_short_range.onnx'
        MinSize     = 400KB
        ExpectedSha = 'bb171799a4497f9d07ef40c7d08acd9b2dd5e7d80ed00bfd0ef5ab2443aab643'
        FallbackUrls = @()
    },
    [PSCustomObject]@{
        Name        = 'face_landmark.onnx'
        Description = 'FaceMesh 468-point landmark model (~2.3 MB)'
        Url         = 'https://raw.githubusercontent.com/IntelliProve/face-detection-onnx/main/fdlite/data/face_landmark.onnx'
        MinSize     = 2MB
        ExpectedSha = '71625efd79fd3ce448ba26db9f7f58e4f37daabf36c81a45a661844e3fdb3118'
        FallbackUrls = @()
    },
    [PSCustomObject]@{
        Name        = 'iris_landmark.onnx'
        Description = 'Iris model — 71 eyelid + 5 iris points per eye (~2.5 MB)'
        Url         = 'https://raw.githubusercontent.com/IntelliProve/face-detection-onnx/main/fdlite/data/iris_landmark.onnx'
        MinSize     = 2.4MB
        ExpectedSha = '1298780b3c203331d4c6b6e1e2ae6e31c29bdbef6fee777ce72d9a5849df0da7'
        FallbackUrls = @()
    }
)

function Get-FileSha256 {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return $null }
    $hash = Get-FileHash -Path $Path -Algorithm SHA256
    return $hash.Hash.ToLower()
}

function Format-Size {
    param([long]$Bytes)
    if ($Bytes -ge 1MB) { return "{0:N2} MB" -f ($Bytes / 1MB) }
    if ($Bytes -ge 1KB) { return "{0:N2} KB" -f ($Bytes / 1KB) }
    return "$Bytes B"
}

function Try-Download {
    param([string]$Url, [string]$Destination, [long]$MinSize)
    $tempPath = "$Destination.partial"
    try {
        Write-Host "  -> $Url" -ForegroundColor DarkGray
        Invoke-WebRequest -Uri $Url -OutFile $tempPath -UseBasicParsing -ErrorAction Stop
        $size = (Get-Item $tempPath).Length
        if ($size -lt $MinSize) {
            Remove-Item $tempPath -Force -ErrorAction SilentlyContinue
            Write-Host "    Got $(Format-Size $size) -- under expected minimum $(Format-Size $MinSize). Likely a redirect/HTML page, not the model." -ForegroundColor Yellow
            return $false
        }
        Move-Item -Path $tempPath -Destination $Destination -Force
        return $true
    }
    catch {
        Remove-Item $tempPath -Force -ErrorAction SilentlyContinue
        Write-Host "    Failed: $($_.Exception.Message)" -ForegroundColor Yellow
        return $false
    }
}

Write-Host ""
Write-Host "Webcam tracking models -- downloader (MediaPipe ONNX via IntelliProve mirror)" -ForegroundColor Cyan
Write-Host "Target: $modelsDir" -ForegroundColor Gray
Write-Host ""

$failures = @()
$shaMismatches = @()

foreach ($m in $models) {
    $target = Join-Path $modelsDir $m.Name
    Write-Host ("[ {0} ] {1}" -f $m.Name, $m.Description) -ForegroundColor White

    if ($VerifyOnly) {
        if (Test-Path $target) {
            $hash = Get-FileSha256 $target
            $size = (Get-Item $target).Length
            $shaOk = ($hash -eq $m.ExpectedSha.ToLower())
            $color = if ($shaOk) { 'Green' } else { 'Yellow' }
            Write-Host "  Present:  $(Format-Size $size)  sha256=$hash  $(if ($shaOk) { '(matches pinned)' } else { '(MISMATCH! pinned: ' + $m.ExpectedSha + ')' })" -ForegroundColor $color
            if (-not $shaOk) { $shaMismatches += $m.Name }
        } else {
            Write-Host "  Missing." -ForegroundColor Red
            $failures += $m.Name
        }
        Write-Host ""
        continue
    }

    if ((Test-Path $target) -and (-not $Force)) {
        $size = (Get-Item $target).Length
        $hash = Get-FileSha256 $target
        $shaOk = ($hash -eq $m.ExpectedSha.ToLower())
        if ($shaOk) {
            Write-Host "  Already present: $(Format-Size $size)  sha256=$hash  (matches pinned, use -Force to re-download)" -ForegroundColor Green
        } else {
            Write-Host "  Already present but SHA MISMATCH: $hash" -ForegroundColor Yellow
            Write-Host "    Pinned:    $($m.ExpectedSha)" -ForegroundColor Yellow
            Write-Host "    Re-download with -Force or investigate." -ForegroundColor Yellow
            $shaMismatches += $m.Name
        }
        Write-Host ""
        continue
    }

    $ok = Try-Download -Url $m.Url -Destination $target -MinSize $m.MinSize
    if (-not $ok) {
        foreach ($fb in $m.FallbackUrls) {
            Write-Host "  Trying fallback..." -ForegroundColor DarkGray
            $ok = Try-Download -Url $fb -Destination $target -MinSize $m.MinSize
            if ($ok) { break }
        }
    }

    if (-not $ok) {
        Write-Host "  FAILED. See Resources\Models\README.md for sourcing alternatives -- drop the file at:" -ForegroundColor Red
        Write-Host "    $target" -ForegroundColor Red
        $failures += $m.Name
        Write-Host ""
        continue
    }

    $size = (Get-Item $target).Length
    $hash = Get-FileSha256 $target
    $shaOk = ($hash -eq $m.ExpectedSha.ToLower())
    if ($shaOk) {
        Write-Host "  Downloaded: $(Format-Size $size)  sha256=$hash  (matches pinned)" -ForegroundColor Green
    } else {
        Write-Host "  Downloaded but SHA MISMATCH: $hash" -ForegroundColor Yellow
        Write-Host "    Pinned:    $($m.ExpectedSha)" -ForegroundColor Yellow
        Write-Host "    Upstream may have changed. Inspect the file before using." -ForegroundColor Yellow
        $shaMismatches += $m.Name
    }
    Set-Content -Path "$target.sha256" -Value $hash -Encoding ASCII
    Write-Host ""
}

if ($failures.Count -eq 0 -and $shaMismatches.Count -eq 0) {
    Write-Host "All models in place and SHA-pinned. Resources\Models\ is ready for the build." -ForegroundColor Green
} elseif ($failures.Count -eq 0) {
    Write-Host "All models downloaded but $($shaMismatches.Count) had SHA mismatches:" -ForegroundColor Yellow
    foreach ($n in $shaMismatches) { Write-Host "  - $n" -ForegroundColor Yellow }
    Write-Host "Investigate before committing." -ForegroundColor Yellow
} else {
    Write-Host "Missing or failed:" -ForegroundColor Red
    foreach ($f in $failures) { Write-Host "  - $f" -ForegroundColor Red }
    Write-Host ""
    Write-Host "Action: open Resources\Models\README.md and follow one of the listed alternative sources." -ForegroundColor Yellow
    exit 1
}
