namespace ConditioningControlPanel.Services.Chaos;

/// <summary>
/// The one tuning block for the hold-to-defuse verb rework and the behavioral bubbles
/// (2026-06-11). Every constant here WILL be rebalanced — keep them named and together,
/// never inline a magic number for any of these in logic code.
/// </summary>
public static class ChaosTuning
{
    // ============================ Focus resource ============================
    // Focus is GENERATED by popping treat-class bubbles and catching white rabbits,
    // and SPENT completing defuse channels. No passive regen, no decay.

    public const double FOCUS_MAX = 100;
    public const double FOCUS_START = 50;

    public const double FOCUS_PER_POP = 10;      // flash, subliminal, any standard treat
    public const double FOCUS_PER_GOLDEN = 12;   // lucky golden bubble
    public const double FOCUS_PER_DROPLET = 4;   // each Gold Digger droplet
    public const double FOCUS_PER_HEART = 10;    // heart catch (on top of +1 resistance)
    public const double FOCUS_PER_RABBIT = 15;   // white rabbit catch
    public const double FOCUS_PER_PRISM = 10;    // prism popped as the treat it mimics
    public const double FOCUS_PER_HEAVY = 15;    // heavy giant (3x pay, slightly more focus)

    // ============================ Defuse channel ============================

    /// <summary>Focus spent per COMPLETED channel (deducted on completion, never on start).</summary>
    public const double DEFUSE_COST = 30;
    /// <summary>Hold this long over a live bubble to deflate it. The fuse pauses meanwhile.</summary>
    public const int DEFUSE_HOLD_MS = 1000;
    /// <summary>Press+release faster than this reads as a CLICK (it still triggers the bubble —
    /// this threshold only picks the click-detonate feedback/bark over the early-release one).</summary>
    public const int CLICK_THRESHOLD_MS = 180;
    /// <summary>Visual shrink floor while channeling (scale 1.0 → this by completion).</summary>
    public const double CHANNEL_MIN_SCALE = 0.55;

    /// <summary>rh_focus_low: seconds of "focus below cost while lives hang on screen" before
    /// the once-per-run warning bark fires.</summary>
    public const double FOCUS_LOW_BARK_SEC = 8;
}
